#include<dirent.h>
#include"flag.c"
#include<fts.h>
#include<grp.h>
#include<pwd.h>
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<sys/stat.h>
#include<time.h>
#include<unistd.h>
#include<zconf.h>